version: 2

jobs:

 build:
   docker:
    - image: cimg/node:current

   steps:
    - checkout
    - setup_remote_docker

    - run:
       name: build client
       command: docker build -t intelligentwater/iwp:client -f ./client/Dockerfile .

    - run:
       name: build server
       command: docker build -t intelligentwater/iwp:server -f ./server/Dockerfile .

    - run:
       name: push client
       command: |
         docker login -u intelligentwater -p 1717intelligent-docker!
         docker push intelligentwater/iwp:client
    - run:
       name: push server
       command: |
         docker login -u intelligentwater -p 1717intelligent-docker!
         docker push intelligentwater/iwp:server